export const FEATURE_FLAGS = {
  PROFILE: false,
  SEARCH: false,
  CR_CORNER: false,
  GROUPS: false,
  CLASSROOM: false,
  INSTITUTIONS: true,
  DEPARTMENTS: true,
  FRIENDS: false,
  COMPETITION: true,
  NOTIFICATIONS: false,
  MESSAGES: false,
  STUDY_HELPER: false,
  OPEN_DISCUSSION: true,
  CAREER_HUB: false,
  STORE: false,
  TUITION: false,
  VIDEOS: false,
  MORE: false,
  SETTINGS: true,
  FILES: false,
  SAVED: false,
  BLOOD_DONATION: false,
};
