export const FRIENDSHIP_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  BLOCKED: "BLOCKED",
};

export const USER_RELATION_STATUS = {
  FRIEND: "FRIEND",
  REQUEST_SENT: "REQUEST_SENT",
  REQUEST_RECEIVED: "REQUEST_RECEIVED",
  BLOCKED: "BLOCKED",
  BLOCKED_BY_THEM: "BLOCKED_BY_THEM",
  SELF: "SELF",
  NONE: "NONE",
};

export const CONNECTION_VISIBILITY = {
  PUBLIC: "PUBLIC",
  CONNECTIONS: "CONNECTIONS",
  ONLY_ME: "ONLY_ME",
};

export const FRIEND_REQUEST_POLICY = {
  EVERYONE: "EVERYONE",
  NOBODY: "NOBODY",
};
