export const GROUP_TYPES = {
  GENERAL: "GENERAL",
  JOBS_CAREERS: "JOBS_CAREERS",
  OFFICIAL_INSTITUTION: "OFFICIAL_INSTITUTION",
};

export const GROUP_PRIVACY = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
  CLOSED: "CLOSED",
};

export const GROUP_ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MODERATOR: "MODERATOR",
  MEMBER: "MEMBER",
};

export const GROUP_MEMBERSHIP_STATUS = {
  JOINED: "JOINED",
  PENDING: "PENDING",
  INVITED: "INVITED",
  BANNED: "BANNED",
};

export const GROUP_JOIN_METHOD = {
  DIRECT_JOIN: "DIRECT_JOIN",
  REQUEST_APPROVAL: "REQUEST_APPROVAL",
  INVITE: "INVITE",
};
