export const INSTITUTION_TYPES = {
  GENERAL_UNIVERSITY: "GENERAL_UNIVERSITY",
  ENGINEERING_UNIVERSITY: "ENGINEERING_UNIVERSITY",
  SCIENCE_TECHNOLOGY_UNIVERSITY: "SCIENCE_TECHNOLOGY_UNIVERSITY",
  MEDICAL_COLLEGE: "MEDICAL_COLLEGE",
  COLLEGE: "COLLEGE",
  POLYTECHNIC_INSTITUTE: "POLYTECHNIC_INSTITUTE",
  SCHOOL: "SCHOOL",
  OTHER: "OTHER",
} as const;

export const INSTITUTION_CATEGORY = {
  PUBLIC: "PUBLIC", // Public University (BUET, DU)
  PRIVATE: "PRIVATE", // Private (NSU, BRAC)
  NATIONAL: "NATIONAL", // National University
  GOVT: "GOVT", // Government College
  NON_GOVT: "NON_GOVT", // Non-government College
};
