export const NOTIFICATION_TYPES = {
  LIKE: "LIKE",
  COMMENT: "COMMENT",
  REPLY: "REPLY",
  FRIEND_REQUEST: "FRIEND_REQUEST",
  FRIEND_ACCEPT: "FRIEND_ACCEPT",
  FOLLOW: "FOLLOW",
  MENTION: "MENTION", // If someone is tagged in the future
  SYSTEM: "SYSTEM", // Messages sent from admin or system

  GROUP_APPROVE: "GROUP_APPROVE",
  GROUP_ROLE_UPDATE: "GROUP_ROLE_UPDATE",
};
