export const ROOM_TYPES = {
  UNIVERSITY: "UNIVERSITY",
  COLLEGE: "COLLEGE",
  COACHING: "COACHING",
  SCHOOL: "SCHOOL",
  GENERAL: "GENERAL",
} as const;

export const ROOM_ROLES = {
  CREATOR: "CREATOR",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
} as const;

export const ROOM_PRIVACY = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
  CLOSED: "CLOSED",
} as const;

export const ROOM_MEMBERSHIP_STATUS = {
  JOINED: "JOINED",
  PENDING: "PENDING",
  REJECTED: "REJECTED",
  BANNED: "BANNED",
} as const;
